function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function dash(value: string | undefined) {
  const v = value?.trim();
  return v ? v : "—";
}

export type CareerEmailApplication = {
  fullName: string;
  email: string;
  phone: string;
  position: string;
  experience?: string;
  link?: string;
  message?: string;
  resumeName: string;
};

function line(label: string, value: string | undefined) {
  return `${label}: ${dash(value)}`;
}

export function buildCareerEmailText(data: CareerEmailApplication) {
  const intro = [
    "A candidate has submitted a job application through the REPLA website.",
    "This email was generated by the online careers form.",
    "",
  ].join("\n");

  const details = [
    line("Name", data.fullName),
    line("Email", data.email),
    line("Phone", data.phone),
    line("Position", data.position),
    line("Years of experience", data.experience),
    line("LinkedIn or GitHub", data.link),
    line("Resume", data.resumeName),
  ].join("\n");

  const note = data.message?.trim();
  return note ? `${intro}${details}\n\nCover letter:\n${note}` : `${intro}${details}`;
}

function detailRow(label: string, valueHtml: string) {
  return `
    <tr>
      <td style="padding:12px 0;border-bottom:1px solid #ececec;width:38%;font-size:12px;letter-spacing:0.06em;text-transform:uppercase;color:#737373;font-family:Arial,Helvetica,sans-serif;">
        ${label}
      </td>
      <td style="padding:12px 0;border-bottom:1px solid #ececec;font-size:15px;line-height:1.5;color:#111111;font-family:Arial,Helvetica,sans-serif;">
        ${valueHtml}
      </td>
    </tr>`;
}

export function buildCareerEmailHtml(data: CareerEmailApplication) {
  const name = escapeHtml(data.fullName);
  const email = escapeHtml(data.email);
  const phone = escapeHtml(data.phone);
  const position = escapeHtml(data.position);
  const experience = escapeHtml(dash(data.experience));
  const resumeName = escapeHtml(data.resumeName);
  const submitted = new Date().toLocaleString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    timeZone: "UTC",
  });

  const link = data.link?.trim();
  const linkHtml = link
    ? `<a href="${escapeHtml(link)}" style="color:#c41e24;text-decoration:underline;word-break:break-all;">${escapeHtml(link)}</a>`
    : "—";

  const coverLetter = data.message?.trim()
    ? escapeHtml(data.message.trim()).replace(/\r\n|\n|\r/g, "<br>")
    : "";

  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>New career application</title>
  </head>
  <body style="margin:0;padding:0;background:#f3f3f4;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f3f3f4;padding:28px 12px;">
      <tr>
        <td align="center">
          <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;background:#ffffff;border-radius:16px;overflow:hidden;border:1px solid #e7e7e9;">
            <tr>
              <td style="background:#0a0a0a;padding:28px 32px 24px;">
                <p style="margin:0 0 10px;font-family:Arial,Helvetica,sans-serif;font-size:12px;letter-spacing:0.16em;text-transform:uppercase;color:#c41e24;">Website careers form</p>
                <h1 style="margin:0;font-family:Arial,Helvetica,sans-serif;font-size:26px;line-height:1.25;color:#ffffff;font-weight:700;">New website job application</h1>
                <p style="margin:10px 0 0;font-family:Arial,Helvetica,sans-serif;font-size:14px;color:#cfcfcf;">${position} · ${submitted} UTC</p>
              </td>
            </tr>
            <tr>
              <td style="height:4px;background:#c41e24;font-size:0;line-height:0;">&nbsp;</td>
            </tr>
            <tr>
              <td style="padding:28px 32px 8px;">
                <p style="margin:0 0 16px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#333333;">
                  A candidate has submitted a job application through the REPLA website. This email was generated by the online careers form.
                </p>
                <p style="margin:0 0 6px;font-family:Arial,Helvetica,sans-serif;font-size:13px;color:#737373;">Applicant</p>
                <p style="margin:0;font-family:Arial,Helvetica,sans-serif;font-size:22px;line-height:1.3;color:#111111;font-weight:700;">${name}</p>
              </td>
            </tr>
            <tr>
              <td style="padding:8px 32px 20px;">
                <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
                  ${detailRow("Email", `<a href="mailto:${email}" style="color:#c41e24;text-decoration:none;">${email}</a>`)}
                  ${detailRow("Phone", `<a href="tel:${phone.replace(/\s+/g, "")}" style="color:#111111;text-decoration:none;">${phone}</a>`)}
                  ${detailRow("Position", position)}
                  ${detailRow("Experience", experience === "—" ? "—" : `${experience} years`)}
                  ${detailRow("Portfolio", linkHtml)}
                  ${detailRow("Resume", `${resumeName}<br><span style="color:#737373;font-size:13px;">Attached to this email</span>`)}
                </table>
              </td>
            </tr>
            ${
              coverLetter
                ? `<tr>
              <td style="padding:0 32px 28px;">
                <p style="margin:0 0 8px;font-family:Arial,Helvetica,sans-serif;font-size:12px;letter-spacing:0.06em;text-transform:uppercase;color:#737373;">Cover letter</p>
                <div style="padding:16px 18px;background:#f7f7f8;border-radius:12px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#111111;">
                  ${coverLetter}
                </div>
              </td>
            </tr>`
                : ""
            }
            <tr>
              <td style="padding:16px 32px 24px;background:#fafafa;border-top:1px solid #ececec;">
                <p style="margin:0;font-family:Arial,Helvetica,sans-serif;font-size:12px;line-height:1.6;color:#8a8a8a;">
                  Source: REPLA website careers form. The resume is attached. Applicant details were also saved to the Career Applicants list in Brevo.
                </p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;
}
